### PR TITLE
Add delegates management commands for the transaction-service

### PR DESCRIPTION
**Pull request by Tritium-VLK**
1. I didn't write this code, but I would love to see it included.

### CODE REVIEW

**Comment by Uxio0** [comment]
@abarmat That's a really good implementation! Why didn't you send a PR?

**Comment by abarmat** [comment]
> @abarmat That's a really good implementation! Why didn't you send a PR?

Just wanted to check first if it made sense for the safe-cli to have that feature, it was my first contribution to the project

**Comment by Uxio0** [comment]
It does, thanks @abarmat !

**Comment by Tritium-VLK** [comment]
Awsome.  Thanks guys.  This was super helpful!

**Pull request merged**
